### PR TITLE
Added functionality to display transparent avatar overlay (ie transparent background)

### PR DESCRIPTION
**Pull request by Interpause**
Modified screenCameraBehaviour.cs to allow using a shader for Graphics.blit(). Created green chroma key transparency shader (in the CameraPlus/Unity folder) as an AssetBundle, loaded as an embeddedResource. Modified Config.cs and setCullingMask() in cameraPlusBehaviour.cs to be able to activate and deactivate this shader as well as cull everything aside from the Avatar layer.

### CODE REVIEW

**Comment by Interpause** [comment]
Currently I am unable to reproduce the issue of some background remaining at the border of the screen camera, could I have some extra information?

**Comment by Snow1226** [comment]
Thank you for the pull request.
With the commits that fixed it, we were able to confirm the resolution of the boundary problem.
Tomorrow we will do a load test, etc. If there is no problem, we will merge.

**Comment by Snow1226** [comment]
Because cam + reloads when switching scenes,
The background is temporarily displayed when the Avatar 　camera switches scenes.
I think it's difficult to deal with this part, so
Can I give up as a specification?
Or do you come up with something?

**Comment by Snow1226** [comment]
Another person told me that using ClearFlags DepthOnly would make the implementation easier.
I'll implement it here, so I won't merge

**Comment by Snow1226** [comment]
I accidentally deleted a different comment.
Thanks to the fix, the boundary problem is solved.
However, there was a problem that the background appeared for a moment each time the scene was switched.
I was worried about dealing with it, another person told me that using ClearFlags DepthOnly would make the implementation easier.
I'll implement it here, so I won't merge

**Comment by Interpause** [comment]
i actually tried implementing using DepthOnly mode at first but could not get it to work properly, my guess being that there is a combination of the weird thing where the camera's rendertexture is actually transparent and how graphics.blit works. would be cool if you could make it work properly so i can learn what the actual problem was

**Comment by Interpause** [comment]
https://answers.unity.com/questions/1396073/camera-clear-color-alpha-ignored.html
^ It may be possible that till now, Unity's cameras ignore alpha channel, which could be why the pixels written to the rendertexture by the camera are transparent.
Since they are transparent, the screen camera that renders the rendertexture, when cleared with depthOnly would not display anything, which was the issue I faced. I am seeing if there is a way to fix it too.

**Comment by Interpause** [comment]
https://forum.unity.com/threads/alpha-in-render-texture-must-be-alpha.746405/#post-4972694
Confirmed that indeed Unity camera still ignores alpha channel on rendertexture completely, not even setting it to opaque.

**Comment by Snow1226** [comment]
Thank you for your support when switching scenes.
ClearFlags Depth Only does not work for the current cam + because depth information has been deleted by Graphics.Blit.
It's better to modify the depth information without using resources, so let's try it.

**Comment by Interpause** [comment]
The rendering camera's depth is preserved in the rendertexture, but the alpha is not because of the camera ignoring alpha channel when writing to rendertexture, so even if Graphics.blit was used with depth information the transparency still will not render for screen camera. It is possible to use depth correctly, allowing for transparency, by using the rendering camera directly to render to screen without intermediate rendertexture, but that would break the ingame camera preview.

**Comment by Interpause** [comment]
Found a workaround to render to both the screen and renderTexture without needing a 2nd camera.
This still involves using the rendering camera instead of the screen camera. This however will break per camera view anti-aliasing in favour of the whole screen obeying Unity's anti-aliasing settings. Not too large of a problem in my opinion considering the limited use case of needing specific control over which camera has anti-aliasing. Might also reduce lag as anti-aliasing is done only once on the screen instead of once per each camera.

**Comment by Interpause** [comment]
I am as of currently unable to figure out how to properly use setTargetBuffers for multiple render textures, so the in-game camera preview for 3rd person is also broken. For general purposes this is a step backwards so I will not be committing to master.

**Comment by Snow1226** [comment]
Thank you for information.
I am also looking for
Although it turns out that depth and alpha can be preserved by processing OnRenderImage of ScreenCameraBehaviour with OnPostRender.
However, the performance was not very good.

**Comment by Snow1226** [comment]
For the time being, as a problem of the Pull Request itself,
-Asset bundles are not desirable considering future maintenance.
-When BeatSaber is running and AvatarOnly flag is set to true, it may terminate abnormally. I think this is due to AssetBundles.
-A transparent background is displayed for a moment when switching between scenes. This is difficult to solve because there is a camera reload.

AssetBundles have a particular problem to merge,
For example, if you need to update this AssetBundle with a future BeatSaber (or UnityEngine) update,
If I or you weren't doing maintenance anymore, the person who took over would be unable to deal with it.

**Comment by Interpause** [comment]
I understand the limitations. Considering I am unable to solve the problems caused by introducing this feature I guess I will close this pull request? Thanks, this was a good learning experience. Have not touched Unity since 4 years ago back when UnityScript was still a thing.

**Pull request closed without merging**
